apiVersion: v1
kind: Namespace
metadata:
  name: nginx-manual
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: app-deployer
  namespace: nginx-manual
rules:
  # Core app resources plus Helm v3 release storage.
  - apiGroups: [""]
    resources:
      - configmaps
      - services
      - secrets
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

  # The replicaset controller (managed by the deployment) will manage the deployments of pods
  # There is no reason our dev user needs to directly create pods.
  - apiGroups: [""]
    resources:
      - pods
    verbs: ["get", "list", "watch"]

  # Give devs access to logs to troubleshoot
  - apiGroups: [""]
    resources:
    - pods/log
    verbs:
    - get

  - apiGroups: ["apps"]
    resources:
      - deployments
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

  # Deployment will create replicasets, No reason for create permission
  - apiGroups: ["apps"]
    resources:
      - replicasets
    verbs: ["get", "list", "watch"]

  - apiGroups: ["networking.k8s.io"]
    resources:
      - ingresses
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

  - apiGroups: ["gateway.networking.k8s.io"]
    resources:
      - gateways
      - httproutes
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

  - apiGroups: ["cert-manager.io"]
    resources:
      - issuers
      - certificates
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: nginx-deployer-app-deployer
  namespace: nginx-manual
subjects:
  - kind: User
    name: nginx-deployer
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: app-deployer
  apiGroup: rbac.authorization.k8s.io
