{{- if eq .Values.route.type "gateway" }}
{{- if .Values.route.gateway.create }}
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ include "webapp.gatewayName" . }}
  labels:
    {{- include "webapp.labels" . | nindent 4 }}
spec:
  gatewayClassName: {{ .Values.route.gateway.gatewayClassName | quote }}
  listeners:
    - name: {{ .Values.route.gateway.httpSectionName | quote }}
      hostname: {{ include "webapp.hostname" . | quote }}
      port: {{ .Values.route.gateway.httpPort }}
      protocol: HTTP
      allowedRoutes:
        namespaces:
          from: Same
    {{- if .Values.tls.enabled }}
    - name: {{ .Values.route.gateway.httpsSectionName | quote }}
      {{- with .Values.route.gateway.listenerHostname }}
      hostname: {{ . | quote }}
      {{- end }}
      port: {{ .Values.route.gateway.httpsPort }}
      protocol: HTTPS
      tls:
        mode: Terminate
        certificateRefs:
          - name: {{ include "webapp.tlsSecretName" . }}
      allowedRoutes:
        namespaces:
          from: Same
    {{- end }}
---
{{- end }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "webapp.fullname" . }}
  labels:
    {{- include "webapp.labels" . | nindent 4 }}
spec:
  parentRefs:
    - name: {{ include "webapp.gatewayName" . }}
      sectionName: {{ .Values.route.gateway.httpSectionName | quote }}
    {{- if .Values.tls.enabled }}
    - name: {{ include "webapp.gatewayName" . }}
      sectionName: {{ .Values.route.gateway.httpsSectionName | quote }}
    {{- end }}
  hostnames:
    - {{ include "webapp.hostname" . | quote }}
  rules:
    - backendRefs:
        - name: {{ include "webapp.fullname" . }}
          port: {{ .Values.service.port }}
{{- end }}
